export const NFT_GATED_VOTE_ABI = [
  "function vote(uint8 collectionId, uint256 tokenId, uint8 choice) external returns (uint256 requestId)",
  "function hasTokenVoted(uint8 collectionId, uint256 tokenId) external view returns (bool)",
  "function getTokenVote(uint8 collectionId, uint256 tokenId) external view returns (uint8)",
  "function tokenVoter(uint8 collectionId, uint256 tokenId) external view returns (address)",
  "function tokenVotingPower(uint8 collectionId, uint256 tokenId) external view returns (uint256)",
  "function tokenPendingRequest(uint8 collectionId, uint256 tokenId) external view returns (uint256)",
  "function getVoteRecord(uint8 collectionId, uint256 tokenId) external view returns (bool hasVoted, uint8 recordedCollectionId, uint256 recordedTokenId, address voter, uint8 choice, uint256 votingPower)",
  "function pendingVotes(uint256 requestId) external view returns (bool exists, address voter, uint8 collectionId, uint256 tokenId, uint8 choice, uint64 createdAt)",
  "function getVoteCount(uint8 choice) external view returns (uint256)",
  "function getChoiceCount(uint8 choice) external view returns (uint256)",
  "function getAllChoiceCounts() external view returns (uint256[] counts)",
  "function leadingChoice() external view returns (uint8 choice, uint256 votes, bool hasVotes, bool isTie)",
  "function quoteRequestValueWei() public view returns (uint256)",
  "function rewardWei() external view returns (uint256)",
  "function maxChoice() external view returns (uint8)",
  "function pollQuestion() external view returns (string)",
  "function choiceLabel(uint8 choice) public pure returns (string)",
  "function maxCollectionId() external pure returns (uint8)",
  "function supportedCollectionIds() external pure returns (uint8[] ids)",
  "function isSupportedCollection(uint8 collectionId) public pure returns (bool)",
  "function collectionLabel(uint8 collectionId) public pure returns (string)",
  "function collectionDisplayLabel(uint8 collectionId) public pure returns (string)",
  "function collectionChainLabel(uint8 collectionId) public pure returns (string)",
  "function collectionVotingPower(uint8 collectionId) public pure returns (uint256)",
  "function debugAdmin() external view returns (address)",
  "function debugOnlyVoidVote(uint8 collectionId, uint256 tokenId) external",
  "function debugOnlyCancelPendingRequest(uint256 requestId) external",
  "function debugOnlyWithdrawSTT(address to, uint256 amountWei) external",
  "function debugOnlyWithdrawAllSTT(address to) external",
  "event VoteRequested(uint256 indexed requestId, address indexed voter, uint8 indexed collectionId, uint256 tokenId, uint8 choice, string url, uint256 requestValueWei)",
  "event VoteRecorded(uint256 indexed requestId, address indexed voter, uint8 indexed collectionId, uint256 tokenId, uint8 choice, uint256 votingPower)",
  "event VoteRejected(uint256 indexed requestId, address indexed voter, uint8 indexed collectionId, uint256 tokenId, uint8 choice, uint256 votingPower, string reason)"
] as const;
